packages:
  - 'app'
  - 'examples/*'
  - 'playground'
  - 'src'
  - 'expo'
  - 'packages/*'

catalog:
  "@tanstack/react-query": "^5.59.20"
  "@types/react": "^18.3.3"
  "@types/react-dom": "^18.3.0"
  react: "^18.3.1"
  react-dom: "^18.3.1"
  typescript: "^5.5.4"
  viem: "^2.22.10"
  wagmi: "^2.14.5"
  globals: "^15.14.0"
  ox: "^0.6.4"
  # expo deps
  expo: "^52.0.0"
  expo-module-scripts: "^4.0.3"
  expo-modules-core: "^2.1.3"
