name: porto

services:
  state:
    build:
      context: "${DOCKER_BUILD_CONTEXT:-https://github.com/ithacaxyz/porto.git#main}"
      dockerfile: ./docker/state/Dockerfile
    environment:
      FOUNDRY_DISABLE_NIGHTLY_WARNING: "true"
    user: root
    volumes:
      - state:/app/shared
    command: ["sh", "-c", "bash ./run.sh"]

  anvil:
    depends_on:
      state:
        condition: service_completed_successfully
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: ["anvil"]
    command: --hardfork osaka --host 0.0.0.0 --port 8545 --accounts 20 --load-state /app/anvil.json
    labels:
      - dev.orbstack.domains=anvil.local
    ports:
      - "8545:8545"
    volumes:
      - state:/app
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:8545"]
      interval: 2s
      retries: 5

  relay:
    depends_on:
      anvil:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.relay
    platform: linux/x86_64
    labels:
      - dev.orbstack.domains=relay.local
    ports:
      - "9119:9119"
    volumes:
      - state:/app
    environment:
      RELAY_MNEMONIC: "test test test test test test test test test test test junk"
      RELAY_FUNDER_SIGNER_KEY: "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
      RELAY_CONFIG: "/app/relay.yaml"
    command: --config /app/relay.yaml --funder-signing-key 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6 --funder-owner-key 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6 --orchestrator 0x700b6A60ce7EaaEA56F065753d8dcB9653dbAD35 --delegation-proxy 0xb19b36b1456E65E3A6D514D3F715f204BD59f431 --simulator 0x8ce361602B935680E8DeC218b820ff5056BeB7af --funder 0xe1Aa25618fA0c7A1CFDab5d6B456af611873b629 --escrow 0xe1DA8919f262Ee86f9BE05059C9280142CF23f48
    healthcheck:
      test: ["CMD", "cast", "rpc", "--rpc-url", "http://localhost:9119", "health"]
      interval: 2s
      retries: 5

  proxy:
    build:
      context: "${DOCKER_BUILD_CONTEXT:-https://github.com/ithacaxyz/porto.git#main}"
      dockerfile: ./docker/proxy/Dockerfile
    labels:
      - dev.orbstack.domains=rpc.local
    environment:
      ANVIL_URL: http://anvil:8545
      RELAY_URL: http://relay:9119
      PORT: 9200
    ports:
      - "9200:9200"
      
volumes:
  state:
